'use strict';

var index = require('../index-73048756.js');

/* src/components/BlogTeaser.svelte generated by Svelte v3.38.3 */

const BlogTeaser = index.create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let { blog } = $$props;
	let { helpers } = $$props;
	if ($$props.blog === void 0 && $$bindings.blog && blog !== void 0) $$bindings.blog(blog);
	if ($$props.helpers === void 0 && $$bindings.helpers && helpers !== void 0) $$bindings.helpers(helpers);

	return `<div class="${"entry"}"><a${index.add_attribute("href", helpers.permalinks.blog({ slug: blog.slug }), 0)}>${index.escape(blog.frontmatter.title)}</a>
  <p>${index.escape(blog.frontmatter.excerpt)}</p></div>`;
});

module.exports = BlogTeaser;
module.exports._css = "";
module.exports._cssMap = "\u002F*# sourceMappingURL=data:application\u002Fjson;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IiJ9 *\u002F";
module.exports._cssIncluded = ["src/components/BlogTeaser.svelte"]
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiQmxvZ1RlYXNlci5qcyIsInNvdXJjZXMiOlsiLi4vLi4vLi4vc3JjL2NvbXBvbmVudHMvQmxvZ1RlYXNlci5zdmVsdGUiXSwic291cmNlc0NvbnRlbnQiOlsiPHNjcmlwdD5cbiAgZXhwb3J0IGxldCBibG9nO1xuICBleHBvcnQgbGV0IGhlbHBlcnM7XG48L3NjcmlwdD5cblxuPGRpdiBjbGFzcz1cImVudHJ5XCI+XG4gIDxhIGhyZWY9e2hlbHBlcnMucGVybWFsaW5rcy5ibG9nKHsgc2x1ZzogYmxvZy5zbHVnIH0pfT57YmxvZy5mcm9udG1hdHRlci50aXRsZX08L2E+XG4gIDxwPntibG9nLmZyb250bWF0dGVyLmV4Y2VycHR9PC9wPlxuPC9kaXY+XG4iXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6Ijs7Ozs7OztPQUNhLElBQUk7T0FDSixPQUFPOzs7O2lFQUlULE9BQU8sQ0FBQyxVQUFVLENBQUMsSUFBSSxHQUFHLElBQUksRUFBRSxJQUFJLENBQUMsSUFBSSx3QkFBTSxJQUFJLENBQUMsV0FBVyxDQUFDLEtBQUs7b0JBQzFFLElBQUksQ0FBQyxXQUFXLENBQUMsT0FBTzs7Ozs7In0=
