'use strict';

var index = require('../../index-73048756.js');

/* src/routes/simple/Simple.svelte generated by Svelte v3.38.3 */

const css = {
	code: "a.svelte-bvr7j8{margin-bottom:1rem;display:inline-block}",
	map: "{\"version\":3,\"file\":\"Simple.svelte\",\"sources\":[\"Simple.svelte\"],\"sourcesContent\":[\"<script>\\n  export let data, request;\\n</script>\\n\\n<style>\\n  a {\\n    margin-bottom: 1rem;\\n    display: inline-block;\\n  }\\n</style>\\n\\n<svelte:head>\\n  <title>{data.title}</title>\\n  <meta name=\\\"description\\\" content=\\\"A Simple Route\\\" />\\n  <link href={request.permalink} rel=\\\"canonical\\\" />\\n</svelte:head>\\n\\n<a href=\\\"/\\\">&LeftArrow; Home</a>\\n\\n<h1>{data.title}</h1>\\n\\n<ul>\\n  {#each data.steps as step}\\n    <li>{@html step}</li>\\n  {/each}\\n</ul>\\n\\n{@html data.content}\\n\"],\"names\":[],\"mappings\":\"AAKE,CAAC,cAAC,CAAC,AACD,aAAa,CAAE,IAAI,CACnB,OAAO,CAAE,YAAY,AACvB,CAAC\"}"
};

const Simple = index.create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let { data } = $$props, { request } = $$props;
	if ($$props.data === void 0 && $$bindings.data && data !== void 0) $$bindings.data(data);
	if ($$props.request === void 0 && $$bindings.request && request !== void 0) $$bindings.request(request);
	$$result.css.add(css);

	return `${($$result.head += `${($$result.title = `<title>${index.escape(data.title)}</title>`, "")}<meta name="${"description"}" content="${"A Simple Route"}" data-svelte="svelte-1aa8ml6"><link${index.add_attribute("href", request.permalink, 0)} rel="${"canonical"}" data-svelte="svelte-1aa8ml6">`, "")}

<a href="${"/"}" class="${"svelte-bvr7j8"}">← Home</a>

<h1>${index.escape(data.title)}</h1>

<ul>${index.each(data.steps, step => `<li><!-- HTML_TAG_START -->${step}<!-- HTML_TAG_END --></li>`)}</ul>

<!-- HTML_TAG_START -->${data.content}<!-- HTML_TAG_END -->`;
});

module.exports = Simple;
module.exports._css = "a.svelte-bvr7j8{margin-bottom:1rem;display:inline-block}";
module.exports._cssMap = "\u002F*# sourceMappingURL=data:application\u002Fjson;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIi4uL3NyYy9yb3V0ZXMvc2ltcGxlL1NpbXBsZS5zdmVsdGUiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IkFBS0csZ0JBQUUsY0FDYyxLQUNmLFFBQVMiLCJzb3VyY2VzQ29udGVudCI6WyI8c2NyaXB0PlxuICBleHBvcnQgbGV0IGRhdGEsIHJlcXVlc3Q7XG48L3NjcmlwdD5cblxuPHN0eWxlPlxuICBhIHtcbiAgICBtYXJnaW4tYm90dG9tOiAxcmVtO1xuICAgIGRpc3BsYXk6IGlubGluZS1ibG9jaztcbiAgfVxuPC9zdHlsZT5cblxuPHN2ZWx0ZTpoZWFkPlxuICA8dGl0bGU+e2RhdGEudGl0bGV9PC90aXRsZT5cbiAgPG1ldGEgbmFtZT1cImRlc2NyaXB0aW9uXCIgY29udGVudD1cIkEgU2ltcGxlIFJvdXRlXCIgLz5cbiAgPGxpbmsgaHJlZj17cmVxdWVzdC5wZXJtYWxpbmt9IHJlbD1cImNhbm9uaWNhbFwiIC8+XG48L3N2ZWx0ZTpoZWFkPlxuXG48YSBocmVmPVwiL1wiPiZMZWZ0QXJyb3c7IEhvbWU8L2E+XG5cbjxoMT57ZGF0YS50aXRsZX08L2gxPlxuXG48dWw+XG4gIHsjZWFjaCBkYXRhLnN0ZXBzIGFzIHN0ZXB9XG4gICAgPGxpPntAaHRtbCBzdGVwfTwvbGk+XG4gIHsvZWFjaH1cbjwvdWw+XG5cbntAaHRtbCBkYXRhLmNvbnRlbnR9XG4iXX0= *\u002F";
module.exports._cssIncluded = ["src/routes/simple/Simple.svelte"]
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiU2ltcGxlLmpzIiwic291cmNlcyI6WyIuLi8uLi8uLi8uLi9zcmMvcm91dGVzL3NpbXBsZS9TaW1wbGUuc3ZlbHRlIl0sInNvdXJjZXNDb250ZW50IjpbIjxzY3JpcHQ+XG4gIGV4cG9ydCBsZXQgZGF0YSwgcmVxdWVzdDtcbjwvc2NyaXB0PlxuXG48c3R5bGU+XG4gIGEge1xuICAgIG1hcmdpbi1ib3R0b206IDFyZW07XG4gICAgZGlzcGxheTogaW5saW5lLWJsb2NrO1xuICB9XG48L3N0eWxlPlxuXG48c3ZlbHRlOmhlYWQ+XG4gIDx0aXRsZT57ZGF0YS50aXRsZX08L3RpdGxlPlxuICA8bWV0YSBuYW1lPVwiZGVzY3JpcHRpb25cIiBjb250ZW50PVwiQSBTaW1wbGUgUm91dGVcIiAvPlxuICA8bGluayBocmVmPXtyZXF1ZXN0LnBlcm1hbGlua30gcmVsPVwiY2Fub25pY2FsXCIgLz5cbjwvc3ZlbHRlOmhlYWQ+XG5cbjxhIGhyZWY9XCIvXCI+JkxlZnRBcnJvdzsgSG9tZTwvYT5cblxuPGgxPntkYXRhLnRpdGxlfTwvaDE+XG5cbjx1bD5cbiAgeyNlYWNoIGRhdGEuc3RlcHMgYXMgc3RlcH1cbiAgICA8bGk+e0BodG1sIHN0ZXB9PC9saT5cbiAgey9lYWNofVxuPC91bD5cblxue0BodG1sIGRhdGEuY29udGVudH1cbiJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiOzs7Ozs7Ozs7Ozs7T0FDYSxJQUFJLGdCQUFFLE9BQU87Ozs7O3lFQVdoQixJQUFJLENBQUMsS0FBSyw2SUFFTixPQUFPLENBQUMsU0FBUzs7OzttQkFLMUIsSUFBSSxDQUFDLEtBQUs7O2lCQUdOLElBQUksQ0FBQyxLQUFLLHdDQUNKLElBQUk7O3lCQUlaLElBQUksQ0FBQyxPQUFPOzs7OzsifQ==
