'use strict';

var index = require('../../index-73048756.js');

/* src/routes/ssr/Ssr.svelte generated by Svelte v3.38.3 */

const Ssr = index.create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let { request } = $$props;
	if ($$props.request === void 0 && $$bindings.request && request !== void 0) $$bindings.request(request);

	return `${($$result.head += `${($$result.title = `<title>Test Title: ${index.escape(request.foo)} ${index.escape(request.bar)}</title>`, "")}<meta name="${"description"}" content="${"Test Description: " + index.escape(request.foo) + " " + index.escape(request.bar)}" data-svelte="svelte-1gpese4"><link${index.add_attribute("href", request.permalink, 0)} rel="${"canonical"}" data-svelte="svelte-1gpese4">`, "")}

These params are generated from the url. They are only available in SSR mode unless the \`all()\` function returns
requests.

<ul><li>foo: ${index.escape(request.foo)}</li>
  <li>bar: ${index.escape(request.bar)}</li></ul>`;
});

module.exports = Ssr;
module.exports._css = "";
module.exports._cssMap = "\u002F*# sourceMappingURL=data:application\u002Fjson;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IiJ9 *\u002F";
module.exports._cssIncluded = ["src/routes/ssr/Ssr.svelte"]
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiU3NyLmpzIiwic291cmNlcyI6WyIuLi8uLi8uLi8uLi9zcmMvcm91dGVzL3Nzci9Tc3Iuc3ZlbHRlIl0sInNvdXJjZXNDb250ZW50IjpbIjxzY3JpcHQ+XG4gIGV4cG9ydCBsZXQgcmVxdWVzdDtcbjwvc2NyaXB0PlxuXG48c3ZlbHRlOmhlYWQ+XG4gIDx0aXRsZT5UZXN0IFRpdGxlOiB7cmVxdWVzdC5mb299IHtyZXF1ZXN0LmJhcn08L3RpdGxlPlxuICA8bWV0YSBuYW1lPVwiZGVzY3JpcHRpb25cIiBjb250ZW50PVwiVGVzdCBEZXNjcmlwdGlvbjoge3JlcXVlc3QuZm9vfSB7cmVxdWVzdC5iYXJ9XCIgLz5cbiAgPGxpbmsgaHJlZj17cmVxdWVzdC5wZXJtYWxpbmt9IHJlbD1cImNhbm9uaWNhbFwiIC8+XG48L3N2ZWx0ZTpoZWFkPlxuXG5UaGVzZSBwYXJhbXMgYXJlIGdlbmVyYXRlZCBmcm9tIHRoZSB1cmwuIFRoZXkgYXJlIG9ubHkgYXZhaWxhYmxlIGluIFNTUiBtb2RlIHVubGVzcyB0aGUgYGFsbCgpYCBmdW5jdGlvbiByZXR1cm5zXG5yZXF1ZXN0cy5cblxuPHVsPlxuICA8bGk+Zm9vOiB7cmVxdWVzdC5mb299PC9saT5cbiAgPGxpPmJhcjoge3JlcXVlc3QuYmFyfTwvbGk+XG48L3VsPlxuIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7Ozs7Ozs7T0FDYSxPQUFPOzs7cUZBSUUsT0FBTyxDQUFDLEdBQUcsa0JBQUcsT0FBTyxDQUFDLEdBQUcsOEZBQ1EsT0FBTyxDQUFDLEdBQUcsdUJBQUcsT0FBTyxDQUFDLEdBQUcsb0VBQ2xFLE9BQU8sQ0FBQyxTQUFTOzs7Ozs0QkFPbkIsT0FBTyxDQUFDLEdBQUc7MEJBQ1gsT0FBTyxDQUFDLEdBQUc7Ozs7OyJ9
